update dwm fibonacci diff url
fixes
```
Notice: /Stage[main]/Fetch_patches/Wget::Fetch[download dwm fibonacci
patch]/Exec[wget-download dwm fibonacci patch]/returns: 2016-07-17
06:47:03 ERROR 404: Not Found.
Error: wget --no-verbose
--output-document="/home/nonroot/.dwm/fibonacci.diff"
"http://dwm.suckless.org/patches/dwm-5.8.2-fibonacci.diff" returned 8
instead of one of [0]
Error: /Stage[main]/Fetch_patches/Wget::Fetch[download dwm fibonacci
patch]/Exec[wget-download dwm fibonacci patch]/returns: change from
notrun to 0 failed: wget --no-verbose
--output-document="/home/nonroot/.dwm/fibonacci.diff"
"http://dwm.suckless.org/patches/dwm-5.8.2-fibonacci.diff" returned 8
instead of one of [0]
```